Feat/challenge 03 loops conditionals
UnPiquito/JavaScript-foundations-challenge-1 pull request #3
Opened 2023-11-04 19:51 UTC by UnPiquito

2023-11-05 20:27 UTC, tictools requested changes
`node_modules` folder should never be pushed to remote repository.

In order to remove it, follow these steps:
* remove `node_modules` folder in your remote repository (branch `feat/challenge_03_loops-conditionals`)
* move to your local repo (same branch) and execute `git pull`
* fix requested changes and push them.

2023-11-05 20:27 UTC, tictools commented on JavaScript-foundations-feat-challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +var numero = 7;
⚠️ FIX: use 🇬🇧, please.

2023-11-05 20:27 UTC, tictools commented on JavaScript-foundations-feat-challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_02.js
> +
If I execute this solution as follows...
```js
const age = 15;

if (age < 3) {
  console.log("You're just a baby!");
} else if (age < 13) {
  console.log("Nice, you're a teenager!");
} else if (age >= 18) {
  console.log("Most places consider you an adult.");
} else {
  console.log("What? How did this happen!?");
}

```
...output is `What? How did this happen!?`

Have you tested this script before pushing it? Is it properly working or is there any error in it?

⚠️ FIX: spot the 🐛 and fix it

2023-11-05 20:27 UTC, tictools commented on JavaScript-foundations-feat-challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i <= 40; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 20:27 UTC, tictools commented on JavaScript-foundations-feat-challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +for (let i = 1; i <= 10; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 20:27 UTC, tictools commented on JavaScript-foundations-feat-challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

This is the output of your script
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 20:27 UTC, tictools commented on JavaScript-foundations-feat-challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +while (i <= 100) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

This is the output of your script
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-12 17:09 UTC, tictools approved these changes

2023-11-12 18:36 UTC, JosepRubio approved these changes
Great job Unai!💥

2023-11-13 17:49 UTC, merged